spring:
  datasource:
    url: jdbc:mariadb://milaxycloud:3306/mvocab
    username: root
    password: kubop4elA@%@mdd8tH
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
